### ISSUE TITLE
v0.8.0. Localization issue

### ISSUE THREAD

**Issue by Matgen84** [chrisknepper/android-messages-desktop#127]
Hi

Thanks for your great job. 

I've a localization issue with latest 0.8.0: no more French language system, only english! (Mojave 10.14.3)

Some solutions, please

**Comment by chrisknepper** [comment]
Hi @Matgen84, do you mean that your computer language is French but you want to spell check in English?

**Comment by Matgen84** [comment]
Hi chrisknepper.
Sorry for my bad english;
my computer use French Language. Latest 0.8.0 don't use my system preference and display only english language in interface: for example "Start" instead of "Démarrer une conversation". Or 02:PM instead of 14:00, and so on... Latest 0.8.0 is only a english version for me.

**Comment by chrisknepper** [comment]
@Matgen84 Thank you. I confirm this is happening with v0.8.0. It looks like a problem with electron 3 and how it does language versus electron 2. I will investigate and try to fix this.

**Comment by chrisknepper** [comment]
Based on some quick testing, this looks like an issue only in Electron 3.x (v0.8.0 of this app uses 3.1.3). For some reason, the web page will only use English or the language of the system when app is built when Electron is 3.1.3. This looks fixed in Electron 4 but I will need to do more testing before I release an update.

Thank you for reporting @Matgen84 😃 🇺🇸 🇫🇷

**Comment by Matgen84** [comment]
Thanks a lot.
