### ISSUE TITLE
[Feature Request] Option to not pop-up message contents in notification

### ISSUE THREAD

**Issue by engineerboy** [chrisknepper/android-messages-desktop#144]
With other messaging apps I have them configured to notify me when new messages are received but to not include the message contents in the notification. This allows me to have the app running even while screen-sharing without risk of inappropriate information popping up at an inopportune time.

Currently I have to remember to close the app before any screen sharing and then re-enable it afterwards.

**Comment by chrisknepper** [comment]
Good idea @engineerboy, I can make that happen!

As an aside, philosophically I feel that Mac/Windows/Linux DEs should provide that setting at the operating system level since they provide the notification framework. For example Android provides the option to hide the content of all notifications on its lock screen.

**Comment by chrisknepper** [comment]
@engineerboy It looks like Google sort of has this as a built-in option already within the app under the 3 dot (settings) menu. That option seems to prevent only the message content from appearing in notifications. My option will additionally allow preventing the name of the contact from appearing.
