### ISSUE TITLE
Links do not open

### ISSUE THREAD

**Issue by dealingwith** [chrisknepper/android-messages-desktop#158]
Andoird Messages version: 1.0.0
OS: MacOS Mojave

This appears to be a regression in 1.0.0. Clicking on a message with a link in it selects the message instead of opening the link.

I confirmed this is not a bug on `messages.google.com`.

I also uninstalled and reinstalled 1.0.0 and the bug persists.

**Comment by jpool-cf** [comment]
Version: 1.0.0
OS: Windows 10

Same issue here, links do not open. Have to copy message text.

**Comment by nelsonni** [comment]
Appears to be attempting to open the URL within Android Messages instead of delegating to an external browser. The last update to the code that handles this was 2 months ago by @chrisknepper: https://github.com/chrisknepper/android-messages-desktop/blob/71fab5adee494cce03d01868fa1ebf1a0f7563b7/src/helpers/webview/input_manager.js#L17-L36
It might be a downstream effect of the updates required for handling the new URL during the **v1.0** update.

**Comment by chrisknepper** [comment]
@dealingwith @jpool-cf @nelsonni Thanks for reporting this, I will take a look ASAP!

**Comment by ffxsam** [comment]
Same issue here. Clicking links does nothing, it just expands the timestamp.

**Comment by chrisknepper** [comment]
I've got the code all ready for this, just need to test it on Windows and Linux later today and should be out tonight.

**Comment by chrisknepper** [comment]
Functionality looks good on Mac Mojave, Windows 10, Ubuntu 18.04. Release 1.0.1 is imminent.
