### ISSUE TITLE
AM is asking for root password on startup

### ISSUE THREAD

**Issue by jjgalvez** [chrisknepper/android-messages-desktop#185]
AM is asking for the root password every time I start it. hitting cancel the application opens and seems to run without issue.
AM 2.0.0
electron 4.0.4
chrome 69.0.3497.106
node 10.11.0
v8 6.9.427.24-electron.0
OS Arch installed with AUR
(https://aur.archlinux.org/packages/android-messages-desktop/)

**Comment by jjgalvez** [comment]
Why is every time I open Android messages I get an error saying authentication is required to run /usr/bin/chown ?  what is trying to run chown and whose ownership is being changed?

**Comment by adk2266** [comment]
Seconded.  Messages 2.0.0 from the .deb release, on Xubuntu 19.04.  Why on earth does it want to chown?

**Comment by johnmmcgee** [comment]
I also am having the issue.  This seems like a major security flaw.

**Comment by ajivoin** [comment]
I don't know the specifics since I didn't do this implementation, but it looks like there was an issue with spellcheck not working properly due to file permissions on Linux.

Here's where the changes were made if you'd like to read the code: https://github.com/chrisknepper/android-messages-desktop/pull/179/commits/178dde906b769dc3a552f574c28b55f0908a6a84

**Comment by chrisknepper** [comment]
Hey all,

The reason the app asks for sudo on Linux is to run a `chown` on the directory where the spelling dictionaries are saved. This was my naive attempt to make the spellcheck work on Linux since prior updates to Electron and its update mechanisms had made those directories not writable.

I believe I have solved this by changing the location of the dictionaries to be the proper Electron location (`userData`) and will release as soon as I can test it properly. Appreciate your patience!

**Comment by chrisknepper** [comment]
The pull request I just opened shows what the sudo prompt does: https://github.com/chrisknepper/android-messages-desktop/pull/199/files

After this change, the app will no longer ask for sudo.

**Comment by jjgalvez** [comment]
That's great thank you. Once the update is available I am going to uninstall the current app and reinstall to make sure all the folder permissions get sorted out correctly




Get Outlook for Android







On Mon, Sep 2, 2019 at 1:14 PM -0400, "Chris Knepper" <notifications@github.com> wrote:












The pull request I just opened shows what the sudo prompt does: https://github.com/chrisknepper/android-messages-desktop/pull/199/files


After this change, the app will no longer ask for sudo.

**Comment by chrisknepper** [comment]
@adk2266 @ajivoin @jjgalvez @johnmmcgee 

This is now fixed as of v3.0.0 which I just released, no more sudo needed or asked for and spell-checking should work. If you encounter any other problems please open a new issue and thanks for being users!
