### ISSUE TITLE
Feature Request: Clicking notifications opens chat

### ISSUE THREAD

**Issue by jacob-swenson** [chrisknepper/android-messages-desktop#20]
On Windows 7 clicking the notifications is not opening the chat. Not sure if this is a new feature or if it's just not working right on 7. Will try on Linux when I'm not on my work computer later tonight.

**Comment by hexeth** [comment]
I do not think he has yet tied in the notifications to anything as this is also happening on Windows 10

**Comment by adriancampos** [comment]
It does seem to open the chat of the person you're speaking with, but doesn't bring the window into focus.
I'm on Windows 10

**Comment by jacob-swenson** [comment]
I can confirm @adriancampos comment. So the feature request would simply be to focus the window on notification click.

**Comment by chrisknepper** [comment]
Hi all,

Thanks for using my app! There are many feature requests involving changing the behavior of notifications. As far as I can tell, because we are using a `Webview` to display Messages for web, Electron cannot control or modify these notifications out of the box, only forward them to the system or block them.

However, I believe there is a way to be able to customize the notifications. I believe we can inject some JavaScript into the `Webview` to modify the browser's `Notification` class and forward them to the Electron process where we can do things like perform actions on click.

I can't put a timeframe on how long this will take yet, but it's definitely something I want to do. And anyone who is reading this with Electron experience, especially involving communication with a `Webview`, I would love tips on this.

**Comment by chrisknepper** [comment]
This has actually been fixed since 0.6.0, but in 0.7.0 the conversation highlighting has been restored, so now clicking a notification will:

- Show the app
- Select/highlight the conversation/chat the notification belongs to

Please open a new issue if this behavior is not to your liking or you find a bug.
