### ISSUE TITLE
Notifications not working in Windows 10 (fixes from Issue #13 didn't solve)

### ISSUE THREAD

**Issue by elijahtlang** [chrisknepper/android-messages-desktop#34]
Just downloaded and installed this program, and when I get a new text I don't receive a notification. Doesn't matter whether the window is minimized or maximized. I have notifications turned on in the app settings as well as in Windows settings. I'm not running Skype or any other VOIP, and the program shortcut is still in my Start Menu. I'm running Windows Home 1803, OS build 17134.137.

**Comment by elijahtlang** [comment]
Tried disabling/reenabling all the notification settings and now it works. Weird.

**Comment by Enricopv** [comment]
Commenting to add a solution not found here or in #13 ,

Turns out I had Focus Assist toggled on, and with priority only, so it ignored any notifications coming from the app. Clicking on it until it was off fixed it for me.

![priority](https://user-images.githubusercontent.com/7062889/43653989-9d9b7694-96fe-11e8-9795-70bf7811c5c0.png)

**Comment by chaw131109-collab** [comment]
Shizuku
