### ISSUE TITLE
Feature Request: Add option to auto-hide the toolbar

### ISSUE THREAD

**Issue by JacobDB** [chrisknepper/android-messages-desktop#6]
Many Windows apps allow you to auto-hide the toolbar, only appearing when the alt key is pressed. I'd love an option to enable this for Android Messages.

**Comment by chrisknepper** [comment]
According to the `BrowserWindow` [docs](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetautohidemenubarhide), this should be a one-line change:

`win.setAutoHideMenuBar(hide)`

I would like to make this a preference so that Windows users can choose which behavior they want.

**Comment by ajivoin** [comment]
@chrisknepper I think I can have a pull request for this together tomorrow if you haven't started already. Where would you want the preference placed?

**Comment by chrisknepper** [comment]
Since this was taken care of by @ajivoin in #29 , I will close this. Release coming soon.
